Add Description how to Start and Configure the Server
upfrontIO/release-server pull request #2
Opened 2017-07-13 10:12 UTC by DaRaFF

2017-07-14 09:13 UTC, mthpvg commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make deployment. Every rancher stack has stacks and every stack has services. If you click on a stack in the rancher gui, you wil
> Every rancher stack has stacks

I don't get what those meta stacks are. I understand that a stack has services and a service has containers.

> `docker-image-name` is the tag of a docker image

Could this be: `docker-image-name` is the **name** of a docker image

2017-07-14 09:16 UTC, mthpvg commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make deployment. Every rancher stack has stacks and every stack has services. If you click on a stack in the rancher gui, you wil
![selection_086](https://user-images.githubusercontent.com/1951875/28206345-cdaa4930-6885-11e7-87ee-bc3a84e993da.jpg)

Just to be sure the service-id is, in this screenshot: `1st615`?

2017-07-14 09:19 UTC, mthpvg approved these changes
Very nice thx.

2017-07-15 15:55 UTC, marcbachmann commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make deployment. Every rancher stack has stacks and every stack has services. If you click on a stack in the rancher gui, you wil
> Every rancher stack has stacks and every stack has services.

Every rancher environment has stacks and every stack has a service.

2017-07-15 15:56 UTC, marcbachmann commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make deployment. Every rancher stack has stacks and every stack has services. If you click on a stack in the rancher gui, you wil
That's the stack id. The service id shows up in the url when you click onto a service.

2017-07-15 15:56 UTC, marcbachmann requested changes
Please fix the typo with the rancher environment.

2017-07-17 06:45 UTC, mthpvg commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make deployment. Every rancher stack has stacks and every stack has services. If you click on a stack in the rancher gui, you wil
Thanks, got it!

2017-07-17 06:46 UTC, mthpvg commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make deployment. Every rancher stack has stacks and every stack has services. If you click on a stack in the rancher gui, you wil
Environment > stack > service > container :ok_hand:

2017-07-17 07:56 UTC, merged

2017-07-17 07:57 UTC, marcbachmann commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make a deployment. Every rancher environment has 1-n stacks, every stack has 1-n services and every service has 1-n containers. I
> Every rancher environment has 1-n stacks

That's wrong again. It has n stacks. There can be empty environments.

2017-07-17 07:59 UTC, DaRaFF commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make a deployment. Every rancher environment has 1-n stacks, every stack has 1-n services and every service has 1-n containers. I
Yes theoretically. But in real life it makes no sense to have a stack with 0 stacks.

2017-07-17 08:01 UTC, marcbachmann commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make a deployment. Every rancher environment has 1-n stacks, every stack has 1-n services and every service has 1-n containers. I
I'd just remove that instead of making a wrong statement.

2017-07-17 08:17 UTC, DaRaFF commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make a deployment. Every rancher environment has 1-n stacks, every stack has 1-n services and every service has 1-n containers. I
Boah today you are overprecise, but I will change it :-)

2017-07-17 08:20 UTC, marcbachmann commented on README.md
> +`<service1>` is a serviceHandle and is later used as an identifier to make a deployment. Every rancher environment has 1-n stacks, every stack has 1-n services and every service has 1-n containers. I
Hehe. maybe sorry.